server:
  port: 8082
  
spring:
  datasource:
      url: jdbc:mysql://localhost:3306/hotelservice
      username: root
      password: 974Akas@
      driver-class-name: com.mysql.cj.jdbc.Driver
  config:
    import: "optional:configserver:http://localhost:8086"
        
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true 
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect 
        
  application:
    name: HOTEL-SERVICE  
     
        
         